version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: poke-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pokedb
      POSTGRES_USER: pokeuser
      POSTGRES_PASSWORD: pokepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo-db:
    image: mongo:7.0
    container_name: poke-mongo-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: pokelogs
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: